version: 2

models:
  - name: Vehicle Info
    description: "Information on the type, speed and distance traveled of the Vehicle"
    columns:
      - name: track_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


models:
  - name: Trajectory Info
    description: "Data about the trajectory(latitude, longitude, and so on) of a vehicle within timestamps"
    columns:
      - name: track_id, time
        description: "The primary key for this table"
        tests:
          - unique
          - not_null          


models:
  - name: orders
    description: "This will be the third model depicting my final tasks"
    columns:
      - name: track_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null          